name: Install mdbook and dependencies

description: Install mdbook with the dependencies we need.

runs:
  using: composite
  steps:
    # The --locked flag is important for reproducible builds. It also
    # avoids breakage due to skews between mdbook and mdbook-svgbob.
    - name: Install mdbook
      run: cargo install mdbook --locked --version 0.4.34
      shell: bash

    - name: Install mdbook-i18n-helpers
      run: cargo install mdbook-i18n-helpers --locked --version 0.1.0
      shell: bash

    - name: Install mdbook-epub
      run: cargo install mdbook-epub --locked --version 0.4.34
      shell: bash

    - name: Install mdbook-external-links
      run: cargo install mdbook-external-links --locked --version 0.1.1
      shell: bash
